---
title: "rCh06"
author: "Win-Vector LLC"
date: "December 10, 2015"
output:
  md_document:
    variant: markdown_github
---

```{r sourceFns}
source('runDir.R')
# Folder where git repo is held
git_repo_root <- "GitHubLearning"
directory_of_home_folder <- gsub(paste0(git_repo_root, ".*"), "", getwd())

```

## Problem 6.1

```{r}
# example 6.1 of section 6.1.1 
# (example 6.1 of section 6.1.1)  : Memorization methods : KDD and KDD Cup 2009 : Getting started with KDD Cup 2009 data 
# Title: Preparing the KDD data for analysis 

folder <- "KDD2009"
setwd(paste0(directory_of_home_folder, "GithubLearning/PracticalDataScienceCh5&6/", folder))

# Read in the data
d <- read.table('orange_small_train.data.gz',  	# Note: 1 
   header=T,
   sep='\t',
   na.strings=c('NA','')) 	# Note: 2 
churn <- read.table('orange_small_train_churn.labels.txt',
   header=F,sep='\t') 	# Note: 3 
d$churn <- churn$V1 	# Note: 4 
appetency <- read.table('orange_small_train_appetency.labels.txt',
   header=F,sep='\t')
d$appetency <- appetency$V1 	# Note: 5 
upselling <- read.table('orange_small_train_upselling.labels.txt',
   header=F,sep='\t')
d$upselling <- upselling$V1 	# Note: 6 



set.seed(729375) 	# Note: 7 
# Add a column of random numbers between 0 and 1
d$rgroup <- runif(dim(d)[[1]])
# Get one group of 90% that is the training set and 10% as the testing set
dTrainAll <- subset(d,rgroup<=0.9)
dTest <- subset(d,rgroup>0.9) 	 



# get a vector of the outcomes
outcomes=c('churn','appetency','upselling')

# Get a vector of just the variable names (setdiff gets rid of the second vector from the first)
vars <- setdiff(colnames(dTrainAll),
   c(outcomes,'rgroup'))

# Take the training set, only select the columns that are in the vars vector and then 
# determine which are chatigorical variables
catVars <- vars[sapply(dTrainAll[,vars],class) %in%
   c('factor','character')] 	

# Identify the variables that are numerical
numericVars <- vars[sapply(dTrainAll[,vars],class) %in%
   c('numeric','integer')] 


# removes the unnecessary tables
rm(list=c('d','churn','appetency','upselling')) 	

# Decide on the outcome that we want to model of the three
outcome <- 'churn' 	

# Indicate which numberical value of the outcome is a positive result
pos <- '1'

# Splitting data into training and calibrarion. Usually not what is done, but it can be done
useForCal <- rbinom(n=dim(dTrainAll)[[1]],size=1,prob=0.1)>0 	# Note: 14 
dCal <- subset(dTrainAll,useForCal)
dTrain <- subset(dTrainAll,!useForCal)

```


# 

```{r}
# example 6.2 of section 6.2.1 
# (example 6.2 of section 6.2.1)  : Memorization methods : Building single-variable models : Using categorical features 
# Title: Plotting churn grouped by variable 218 levels 


table218 <- table(
   Var218=dTrain[,'Var218'], 	# Note: 1 
   churn=dTrain[,outcome], 	# Note: 2 
   useNA='ifany') 	# Note: 3 
print(table218)
```

